// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvAHnsZFqtwQ1-rhWkD870ifye4VHh8s',
    appId: '1:175668662676:web:838c384e286683d0d5bf81',
    messagingSenderId: '175668662676',
    projectId: 'newmobilapp',
    authDomain: 'newmobilapp.firebaseapp.com',
    storageBucket: 'newmobilapp.appspot.com',
    measurementId: 'G-S6TSJW1C86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-OXgvH1Q7QhPgJYctY88RWnX78MUcr8',
    appId: '1:175668662676:android:23f69519d9508a3fd5bf81',
    messagingSenderId: '175668662676',
    projectId: 'newmobilapp',
    storageBucket: 'newmobilapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60WzzXvgQBKMsPx-RWm2yxTVGcGvUJh4',
    appId: '1:175668662676:ios:02230ffa15dbddffd5bf81',
    messagingSenderId: '175668662676',
    projectId: 'newmobilapp',
    storageBucket: 'newmobilapp.appspot.com',
    iosClientId: '175668662676-8psgg75v4idqcppkna6k7qu32cefm32b.apps.googleusercontent.com',
    iosBundleId: 'com.goril.newmobilapp',
  );
}
